### ISSUE TITLE
Errors Verify RCT ver 006

### ISSUE THREAD

**Issue by mathjo** [dagnall53/RocClientThrottle#1]
Generaal:
Arduino:1.8.8 (Windows Store 1.8.19.0) (Windows 10), Board:"NodeMCU 1.0 (ESP-12E Module), 80 MHz, Flash, Enabled, 4M (no SPIFFS), v2 Lower Memory, Disabled, None, Only Sketch, 115200"

The following errors at Verify; Ver 006 is used

- MQTT.h:21:1 error: ‘PubSubClient’ does not name a type

- MQTT.h In function ‘void MQTTTocnetSend(char*, uint8_t)’

- MQTT.cpp:701:3: error: 'client' was not declared in this scope
   client.publish(topic, payload, Length);

- MQTT.cpp: In function 'void MQTTSend(String, String)':

- MQTT.cpp:708:3: error: 'client' was not declared in this scope
   client.publish(topic.c_str(), payload.c_str(), Length);

- MQTT.cpp: In function 'void MQTT_Setup()':

- MQTT.cpp:716:3: error: 'client' was not declared in this scope
   client.setServer(mosquitto, 1883);   // Hard set port at 1833

- MQTT.cpp: In function 'boolean MQTT_Connected()':

- MQTT.cpp:723:10: error: 'client' was not declared in this scope
   return client.connected();

- MQTT.cpp: In function 'void MQTT_Loop()':

- MQTT.cpp:727:5: error: 'client' was not declared in this scope
     client.loop(); //gets wifi messages etc..

- MQTT.cpp: In function 'void DebugMsgSend(String, String)':

- MQTT.cpp:749:7: error: 'client' was not declared in this scope
   client.publish(topic.c_str(), DebugMsgLocal, strlen(DebugMsgLocal));

- MQTT.cpp:753:7: error: 'client' was not declared in this scope
    client.publish(topic.c_str(), DebugMsgLocal, strlen(DebugMsgLocal));

- MQTT.cpp:757:7: error: 'client' was not declared in this scope
   client.publish(topic.c_str(), DebugMsgLocal, strlen(DebugMsgLocal));

 - MQTT.cpp: In function 'void reconnect()':

 - MQTT.cpp:801:11: error: 'client' was not declared in this scope
   while (!client.connected()) {

exit status 1
Fout bij het compileren voor board NodeMCU 1.0 (ESP-12E Module)
Have I something missed?

Mathjo

**Comment by HenningS81** [comment]
Hi Mathjo,

I don't know if it is still an issue. But there a several MQTT libs around. Here you should use this one: https://pubsubclient.knolleary.net

Best,

Henning

**Comment by dagnall53** [comment]
@mathjo @HenningS81  
Sorry i missed this issue, but I got no advisory  email message from github. ( or it got lost) 
Henning is correct. 
You must have the pubsub library installed in your arduino libraries, and MUST make a small change to it to allow the huge Rocrail service messages to be recieved. 
The change is noted in mqtt.cpp line 8 
You should also check you have all the other libraries i have used installed, or you will get strange error messages. Use the arduino find to look for #include and you should see them all. I have tried to put http references against them all, but see i missed the reference for pubsubclient, but Henning has it in his note. 
I will keep a look out for any response. 
Can you also make sure you have the latest version of the code as I was modifying it around the time you sent the issue.
Again, sorry for the delay, and thanks Henning for adding to the conversation.
Good luck
Dagnall

+edit ..a bit more on Libraries required to compile with Arduino..
see the read me, ;-)  
specifically : https://github.com/dagnall53/RocClientThrottle#compiling

**Comment by mathjo** [comment]
Dagnall, Henning,

Thanks for your attention and support. Problems (ver 6 and ver 7) have been
resolved in Dec 2018 by Dagnall (mail). I checked MQTT and worked. Issue is
solved. PS I didn't get a picture at the time!
At ver 25 for NodeMCU (ESP8266) I also have no picture. Is the dev. Board
defective? I tried another sketch, result display works.

Sincerely,

Mathjo

Op zo 3 feb. 2019 om 23:11 schreef dagnall <notifications@github.com>:

**Comment by dagnall53** [comment]
@mathjo I changed the display at one point to a simpler "no picture" display, but its easy to change back to the picture display: 
There are two functions "OLED_5_line_display_p" and "OLED_5_line_display". The one with _p displays the picture..  I checked the code on github and it should be calling the "with picture" version in NVsettingsInterface.cpp line 56,  so you should be seeing the picture..  (at least before you select a loco).

If its not showing the picture but is showing text, I am very confused.. It may be that your Terriers file has become corrupted, or your copy of the code is not calling OLED_5_line_display_p in line 56 ?.. 

Any detective work you can do would be appreciated.

I will close this "Errors" issue, but please open another if this picture issue persists!. 
PS this time Github emailed me successfully!

**Comment by mathjo** [comment]
@dagnall I ment with "no picture" "no display". Sorry. Your suggestions: 1)
line 56 in NVSettingInterface.cpp is correct and is calling
OLED_5_line_display_p and 2) Terrier.h is not corrupted.
Should I open a issue for this case (no display)?

Mathjo

Op ma 4 feb. 2019 om 16:02 schreef dagnall <notifications@github.com>:

**Comment by dagnall53** [comment]
@mathjo 
I think you are saying that you have no display at all (?) 
Ie No writing and No picture? 
If so then a new issue please.. Can you describe in great detail (!) exactly what works and what does not..
Which OLED board are you using, and does it work with other sketches? 
If it works with other sketches, can you first check that the OLED connections are correct .. Check both the sketch that works and my sketch to see if they differ please. Mainly check that OLED_SDA, OLED_SCL are both the same in booth sketches.. Also check the OLED address (0x3c) in the setup (line 30 in my ino.) Yours might be different.. 

Different boards do have different addresses. It would be a good idea to run an address finder sketch to find what address it is.. something like https://github.com/todbot/arduino-i2c-scanner/blob/master/I2CScanner/I2CScanner.ino 
or https://github.com/hallard/Scan-I2C-WiFi

I will close this thread so you can open  a new one..
