### ISSUE TITLE
Error Verify RCT ver 007

### ISSUE THREAD

**Issue by mathjo** [dagnall53/RocClientThrottle#2]
Hi,

I saw the latest version 007. Verify gives only one error:

General:
Arduino: 1.8.8 (Windows Store 1.8.19.0) (Windows 10), Board: "NodeMCU 1.0 (ESP-12E Module), 80 MHz, Flash, Enabled, 4M (no SPIFFS), v2 Lower Memory, Disabled, None, Only Sketch, 115200"

- MQTT.cpp:13:26: fatal error: PubSubClient.h: No such file or directory
   #include <PubSubClient.h>

compilation terminated.

exit status 1
Error compiling for board NodeMCU 1.0 (ESP-12E Module).

I don’t know how to resolve. Thks for your respons.

Mathjo

**Comment by dagnall53** [comment]
Have you got the pubsubclient library installed? And also Its very important to increase the size that the MQTT interface can use: see the comment in read.me

**Comment by mathjo** [comment]
Idd the pubsubnet library wasn't installed. No errors anymore, thanks for
the support.

PS The MQTT size is increased.


Marcel

Op vr 28 dec. 2018 om 21:06 schreef dagnall <notifications@github.com>:

**Comment by dagnall53** [comment]
Cheers, Glad it works. 
There is a very small bug related to the lights showing off on the throttle sometimes when the loco lights are actually on, but I hope to find it soon.
