### ISSUE TITLE
No display at Wemos ESP8266 NodeMCU Wifi 18650 battery 0,96 OLED

### ISSUE THREAD

**Issue by mathjo** [dagnall53/RocClientThrottle#3]
I have a WeMos ESP-12F Motherboard ESP8266 Mini-WiFi NodeMCU Module 18650 Battery OLED. After upload it only shows  black display. With another sketch "PacketMonitor-Master" the display is normal. 

At PacketMonitor display address is 0x3c, SDA-pin = 5 and SCL-pin = 4. At RocClientThrottle it is  SSD1306  display(0x3c, OLED_SDA, OLED_SCL); In "Secret.h" 
static const uint8_t OLED_SCL = 4;  //also known as D2 on esp 8266, but
static const uint8_t OLED_SDA = 5;  // also known as D1 on esp 8266. There is no difference at the display-address, or SDA or SCL-pins.

Following your suggestion I did the "Scan-I2C-Wifi" which shows the following information:
19:40:50.501 -> Booting on ESP8266_NODEMCU
19:40:50.501 -> Scan-I2C-WiFi.ino on ESP8266_NODEMCU Feb  5 2019 19:30:33
19:40:50.501 -> ESP8266 Core Version 2_5_0_BETA2
19:40:50.501 -> Searching for device at address 0x3C No I2C devices found
19:40:50.501 -> Searching for device at address 0x3D No I2C devices found
19:40:50.595 -> WiFi scan start
19:40:52.845 -> scan done
19:40:52.845 -> I2C scan start
19:40:53.032 -> Scanning I2C bus ...
19:40:53.032 -> No I2C devices found
19:40:53.032 -> scan done
19:40:53.032 -> connecting to UPC24xxxxxx with psk xxxxxxxxxxx
19:40:57.390 -> OK from ScanI2CWiFi-B96F@192.168.xx.xx
19:40:57.390 -> Setup done
19:41:07.372 -> Setting readyForUpdate to true
19:41:07.372 -> Scanning I2C bus ...
19:41:07.372 -> No I2C devices found

Do you have a solution for my display problem?
kind regards,
mathjo

**Comment by dagnall53** [comment]
That is very very strange. From what you say, my  code and scan 12c use the same functions and do not work, but packet monitor does!  But at least that gives some ideas for where and how  to search for the 'proper' solution.
Can you check that the library calls for packet monitor and scan i2c are calling the same libraries.. And that they are up to date? The only thing i can think of at the moment is that they used different libraries, ( one for packet monitor that works) and a different one for i2cscan and my code that does not.. 
It may be that you have multiple library locations and arduino is confusing us? I try to keep all my libraries in c/arduino/libraries to avoid confusion, but I think i have seen it try to keep some in documents and also in the appdata arduino15/libraries folder. 
Sorry not to be more help.
Dagnall

**Comment by dagnall53** [comment]
@mathjo. Were you able to see if your compiler was using different libraries? I was able today to re load the throttle on my test esp8266 and it worked fine.. 
Dagnall

**Comment by mathjo** [comment]
Dagnall, I have a Windows10 pc. I've uninstalled Arduino. Also all
libraries, packages removed. Again Arduino installed. Board-Library
installed for ESP8266. All libraries required for RCThrottle installed.
Verify and upload done and the result is nothing on display. On the serial
monitor only dredge (not readable characters) is available.

The esp8266-packet monitor uploaded and worked right away. (No additional
libraries are required).

PS I used at Settings board: NodeMCU 1.0 (ESP12-12th module)

It is certain that no different libraries have been used now. It seems most
likely that the esp8266-board is not good.

Thanks for support and in thinking up.

mathjo

Op do 7 feb. 2019 om 23:22 schreef dagnall <notifications@github.com>:

**Comment by dagnall53** [comment]
Mathjo, very sorry that you are still having difficulties with the throttle. I hope that when you try a new board and oled, you find it works, but it is surprising you are having serial port issues as well as display trouble. As you say, the board probably has faults. 

I am nearly finished with an upgrade to my espwifi rocnode software that allows it to use esp32 and have a node running an oled as well as 16 io. It needs more testing, but i will upload it soon.

**Comment by mathjo** [comment]
@Dagnall Probably better to just wait for the upgrade for the ESP32 with
OLED and 16io. Then I buy a ESP32...... instead ESP8266 Wemos Oled 18650
Battery.

Thanks for the support. mathjo

Op vr 8 feb. 2019 om 14:30 schreef dagnall <notifications@github.com>:

**Comment by dagnall53** [comment]
@mathjo I think you may have mis-understood my last note on ESP32.. 
This Throttle code IS already ESP32 compatible and works.. Also on the ESP32 board, the display is turned 90 degrees so is "nicer" to use. 
(I was referring to my other "ESPwifiRocnetSound" project when I said I was working on ESP32 compatibility, Sorry if that confused you)
I also had another thought that may help. Out of the three ESP8266 +oled+battery boards that I have had delivered, only one was completely undamaged. TWO had slight cracks on the edge of the OLED that in one made the oled completely non functional, and on another it caused only half the lines of the OLED to work. 
I think the physical design of the combination OLED+battery board is poor, as the oled is unsupported and close to the edge of the PCB so can get knocked quite easily. 
I will close this issue, but feel free to message me if you need more help.
Can I also suggest checking / asking for help in the Rocrail Forums? , Especially [https://forum.rocrail.net/viewtopic.php?p=187705#p187705]
Dagnall
