### ISSUE TITLE
Battery Monitor

### ISSUE THREAD

**Issue by mathjo** [dagnall53/RocClientThrottle#4]
Dear Dagnall,

In Read.me is listed under Hardware for the Battery Monitor for ESP32 boards that has to be 2 resistors and pin 36 should be used for analog input. In secret. H is indicated "const int ADC_IN = 35". It seems to be conflicting. I have not connected this yet!
Please comment. 

Sincerely

Mathjo

**Comment by dagnall53** [comment]
@mathjo Thanks.
You are correct, I have now changed the readme.
On the ESP32 I used pin 35.
